# Generated by Django 5.1.7 on 2025-03-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_image_project_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
