# Generated by Django 5.1.7 on 2025-03-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_content_news_link_remove_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
